package com.spentoo.loan.dto;

import com.spentoo.payment.dto.PaymentMethodDTO;
import lombok.Data;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

@Data
public class LoanInstallmentDTO {

    private Integer installmentId;
    private Integer loanId; // Parent loan ID
    private BigDecimal amountPaid;
    private LocalDate paymentDate;
    private PaymentMethodDTO paymentMethod; // Details of the payment method
    private boolean isAutoGenerated;
    private String notes;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;
}
