package com.spentoo.loan.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.spentoo.payment.model.PaymentMethod;
import jakarta.persistence.*;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

@Data
@ToString(exclude = {"loan"})
@EqualsAndHashCode(exclude = {"loan"})
@Entity
@Table(name = "LoanInstallment")
public class LoanInstallment {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "InstallmentID")
    private Integer installmentId;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "LoanID", nullable = false)
    @JsonIgnore
    private Loan loan;

    @Column(name = "AmountPaid", nullable = false, precision = 10, scale = 2)
    private BigDecimal amountPaid;

    @Column(name = "PaymentDate", nullable = false)
    private LocalDate paymentDate;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "PaymentMethodID") // Optional, can be null for cash
    private PaymentMethod paymentMethod;

    @Column(name = "IsAutoGenerated", nullable = false)
    private boolean isAutoGenerated = false;

    @Column(name = "Notes", length = 255) // Using VARCHAR(255) for consistency
    private String notes;

    @CreationTimestamp
    @Column(name = "CreatedAt", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @UpdateTimestamp
    @Column(name = "UpdatedAt", nullable = false)
    private LocalDateTime updatedAt;
}
